# Generated by Django 4.2.1 on 2024-01-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_chatmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="full_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True, default="default.jpg", null=True, upload_to="user_images"
            ),
        ),
    ]
